### ISSUE TITLE
South migrations don't work with Django 1.6

### ISSUE THREAD

**Issue by mrmachine** [edoburu/django-fluent-pages#33]
Looks like something to do with the updated transaction management. Something might be turning `autocommit` off and not turning it back on, but I can't figure out what.

You can work around it (on a fresh install, at least) by doing `./manage.py syncdb --all` and then `./manage.py migrate --fake`, but this probably won't work if upgrading an existing project from Django 1.5 to 1.6.

Here's the traceback:

```
Running migrations for fluent_pages:
 - Migrating forwards to 0009_multisite_drop_cached_url_unique.
 > fluent_pages:0001_initial
 > fluent_pages:0002_rename__expire_date__publication_end_date
 > fluent_pages:0003_add_urlnode_indexes
 > fluent_pages:0004_remove_sort_order
 > fluent_pages:0005_add_translation_model
 > fluent_pages:0006_migrate_translated_fields
 - Migration 'fluent_pages:0006_migrate_translated_fields' is marked for no-dry-run.
 > fluent_pages:0007_remove_untranslated_fields
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: fluent_pages:0007_remove_untranslated_fields
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/south/migration/migrators.py", line 254, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/south/migration/migrators.py", line 329, in migrate_many
    result = self.migrate(migration, database)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/Users/tailee/.virtualenvs/django-fluent-demo/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/Users/tailee/.virtualenvs/django-fluent-demo/src/django-fluent-pages/fluent_pages/migrations/0007_remove_untranslated_fields.py", line 26, in forwards
    clear_app_reverse_cache()
  File "/Users/tailee/.virtualenvs/django-fluent-demo/src/django-fluent-pages/fluent_pages/urlresolvers.py", line 127, in clear_app_reverse_cache
    for model in page_type_pool.get_model_classes():
  File "/Users/tailee/.virtualenvs/django-fluent-demo/src/django-fluent-pages/fluent_pages/extensions.py", line 297, in get_model_classes
    self._import_plugins()
  File "/Users/tailee/.virtualenvs/django-fluent-demo/src/django-fluent-pages/fluent_pages/extensions.py", line 401, in _import_plugins
    import_apps_submodule("page_type_plugins")
  File "/Users/tailee/.virtualenvs/django-fluent-demo/src/django-fluent-pages/fluent_pages/utils/load.py", line 53, in import_apps_submodule
    import_module('.' + submodule, app)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/tailee/.virtualenvs/django-fluent-demo/src/django-fluent-pages/fluent_pages/pagetypes/fluentpage/page_type_plugins.py", line 7, in <module>
    class FluentPagePlugin(PageTypePlugin):
  File "/Users/tailee/.virtualenvs/django-fluent-demo/src/django-fluent-pages/fluent_pages/extensions.py", line 276, in register
    ct_id = plugin_instance.type_id                  # DB query first before updating self, query may fail.
  File "/Users/tailee/.virtualenvs/django-fluent-demo/src/django-fluent-pages/fluent_pages/extensions.py", line 139, in type_id
    raise DatabaseError("Unable to fetch ContentType object, is a plugin being registered before the initial syncdb? (original error: {0})".format(str(e)))
django.db.utils.DatabaseError: Unable to fetch ContentType object, is a plugin being registered before the initial syncdb? (original error: Your database backend doesn't behave properly when autocommit is off. Turn it on before using 'atomic'.)
```

**Comment by vdboor** [comment]
Sorry for not updating this issue before! I expect this bug to be fixed, as the new 0.9 release solves many migration issues, and even offers 1.7/1.8 support.
