### ISSUE TITLE
AttributeError: 'TextItem_AutoInline' object has no attribute 'queryset'

### ISSUE THREAD

**Issue by bashu** [edoburu/django-fluent-pages#64]
latest stable CMS with django 1.8, got this after trying to copy content from other language

```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/polymorphic/admin.py", line 346, in subclass_view
    return resolvermatch.func(request, *resolvermatch.args, **resolvermatch.kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/fluent_contents/admin/placeholdereditor.py", line 242, in get_placeholder_data_view
    'formset_forms': self._get_object_formset_data(request, obj),
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/fluent_contents/admin/placeholdereditor.py", line 259, in _get_object_formset_data
    formset_forms = self._get_contentitem_formset_html(request, obj, FormSet, inline, placeholder_slots)
  File "/Users/bashu/Projects/django-sigma-cms-demo/virtualenv/lib/python3.4/site-packages/fluent_contents/admin/placeholdereditor.py", line 273, in _get_contentitem_formset_html
    formset = FormSet(instance=obj, prefix='', queryset=inline.queryset(request))
AttributeError: 'TextItem_AutoInline' object has no attribute 'queryset'
```

**Comment by vdboor** [comment]
Hi!

I've solved this in a slightly different way, by changing the source of the call instead (see a1367c7e13a60b1f97a9e0a6ea7770c97caa9196).

Thanks for reporting this issue!
