### ISSUE TITLE
DoesNotExist: Page does not have a translation for the current language!

### ISSUE THREAD

**Issue by bashu** [edoburu/django-fluent-pages#84]
Deleting PageLayout gave me this:

```python
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/options.py", line 583, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1511, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1282, in response_action
    response = func(self, request, queryset)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/actions.py", line 37, in delete_selected
    queryset, opts, request.user, modeladmin.admin_site, using)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 153, in get_deleted_objects
    to_delete = collector.nested(format_callback)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 211, in nested
    roots.extend(self._nested(root, seen, format_callback))
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 194, in _nested
    children.extend(self._nested(child, seen, format_callback))
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 196, in _nested
    ret = [format_callback(obj)]
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 126, in format_callback
    force_text(obj))
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/utils/encoding.py", line 85, in force_text
    s = six.text_type(s)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/fluent_pages/models/db.py", line 653, in __str__
    return self.title or self.safe_translation_getter('slug', u"#{0}".format(self.pk), any_language=True)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/parler/fields.py", line 88, in __get__
    translation = instance._get_translated_model(use_fallback=True, meta=meta)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/parler/models.py", line 505, in _get_translated_model
    "{0} ID #{1}, language={2}{3}".format(self._meta.verbose_name, self.pk, language_code, fallback_msg or ''
DoesNotExist: Page does not have a translation for the current language!
Page ID #6, language=en (tried fallbacks en)
Attempted to read attribute title.
```

**Comment by bashu** [comment]
can be closed?
